name: release-please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.PROJEN_APP_ID }}
          private-key: ${{ secrets.PROJEN_APP_PRIVATE_KEY }}
          permission-pull-requests: write
          permission-contents: write
      - uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          token: ${{ steps.generate_token.outputs.token }}